### PR TITLE
Update build procedure

### PR DESCRIPTION
**Pull request by Marlin-Na**
No need to run `install-symengine.R` manually. The configure script will now check whether SymEngine is installed on system path, if not, it will install SymEngine to a temporary directory and generate `Makevars`.

Related #60 

TODO:
- [ ] Update README instructions
- [ ] Update travis CI script

### CODE REVIEW

**Comment by mattfidler** [comment]
Do you need something similar for mac?  If so then maybe I can help

**Comment by Marlin-Na** [comment]
@mattfidler Thanks, I guess the package should be able to build on Mac as long as cmake and GMP,MPFR,MPC libraries exist on the system. GMP,MPFR,MPC libraries are available as static libraries on CRAN's build machine for Mac OS (http://mac.r-project.org/libs/).

**Comment by mattfidler** [comment]
I'm assuming a pull from the master branch would be sufficient?

**Comment by Marlin-Na** [comment]
@mattfidler This PR is the code submitted to CRAN and I would like to merge it once the package is accepted.

**Comment by mattfidler** [comment]
So do a merge against this branch then?

**Comment by Marlin-Na** [comment]
I am assuming you want to test it locally? Then you need to merge my branch `cran` at https://github.com/Marlin-Na/symengine.R/tree/cran

**Comment by mattfidler** [comment]
Ok.  Thanks.  I will test on a mac and see weather I can help here.

Thanks for taking this to cran.  I like symengine's speed much better than sympy's

**Comment by Marlin-Na** [comment]
@mattfidler To clarify, with this PR, the package can be installed on Mac (via `devtools`) with installed cmake, gmp lib, mpfr lib and mpc lib (installed with Homebrew). It has been at least tested on my machine. However, my concern is that whether package can be built as binary package on CRAN's machine. If not, e.g. there are some issues with CRAN's version of gmp/mpfr/mpc static libraries, we may need to take the approach similar to what we do on Windows (see `src/Makevars.win`). The package currently can pass CRAN's pre-test but I am not sure if it has been tested against CRAN's building procedure for Mac OS.

**Comment by mattfidler** [comment]
Ah.  I see.  That makes sense.  Sigh.  I wish they had some way to reproduce the CRAN machines locally.  

What about solaris?  Did you do anything for them.  They can be picky about it.

**Comment by Marlin-Na** [comment]
@mattfidler Not really be able to test it, though I assume it should work with the dependencies installed. I have tried to use R-hub to test on solaris, but they don't have `cmake`.

**Comment by mattfidler** [comment]
Thanks.  I have tried to get a working solaris running and have run into a road block multiple times.  Perhaps the `cmake` requirement will save this requirement.

**Comment by isuruf** [comment]
For cmake build, should we add `-DWITH_SYMENGINE_THREAD_SAFE=yes`?

**Comment by Marlin-Na** [comment]
@isuruf I think R is single-threaded and we are not using multi-threaded code in C/C++. I guess it should be unnecessary?

**Comment by isuruf** [comment]
Make sense. Thanks for the info.

**Pull request merged**
