### PR TITLE
Add support for windows (moved)

### PR DESCRIPTION
**Pull request by Marlin-Na**

### CODE REVIEW

**Comment by Marlin-Na** [comment]
Hi @isuruf , Is there any recent build of window binaries instead of SymEngine version 0.3.0, which I may use it temporarily before next SymEngine release? Some functions in the R wrapper depends on the more recent version of SymEngine. And the [win-builder](https://win-builder.r-project.org/) of CRAN lacks tools (cmake) to build from source.

**Comment by isuruf** [comment]
You can use the ones at https://anaconda.org/symengine/symengine/files, note that you'll need gmp, mpfr, mpc found at https://anaconda.org/conda-forge/gmp/files, https://anaconda.org/conda-forge/mpfr/files, https://anaconda.org/conda-forge/mpc/files

**Comment by certik** [comment]
@Marlin-Na thanks for working on this. Let us know when this is ready.

**Comment by Marlin-Na** [comment]
Several notes:
1. Error on win-builder. Download from anaconda.org failed, previously I have tried download symengine release binaries from github, which works. Maybe I can try temporally host one on github?
```
* installing *source* package 'symengine' ...
** libs

*** arch - i386
rm -f interface.o symengine.dll 
"D:/RCompile/recent/R/bin/i386/Rscript.exe" "../tools/winlibs.R"
trying URL 'https://anaconda.org/symengine/symengine/0.3.0.353.g22cef70
/download/win-32/symengine-0.3.0.353.g22cef70-vc14_0.tar.bz2'
Error in download.file(link, "symenginelib.tar.bz2", quiet = FALSE) : 
  cannot open URL 'https://anaconda.org/symengine/symengine/0.3.0.353.g
22cef70/download/win-32/symengine-0.3.0.353.g22cef70-vc14_0.tar.bz2'
Calls: download_symengine -> download.file
In addition: Warning message:
In download.file(link, "symenginelib.tar.bz2", quiet = FALSE) :
  InternetOpenUrl failed: 'Die Serververbindung konnte nicht
hergestellt werden.'
Execution halted
make: *** [winlibs] Error 1
ERROR: compilation failed for package 'symengine'
* removing 'd:/RCompile/CRANguest/R-devel/lib/symengine'
In R CMD INSTALL
```

2. Appveyor error
What does `LoadLibrary failure:  The specified procedure could not be found.` imply?

```
* installing *source* package 'symengine' ...
** libs
rm -f interface.o symengine.dll 
"c:/R/bin/i386/Rscript.exe" "../tools/winlibs.R"
trying URL 'https://anaconda.org/symengine/symengine/0.3.0.353.g22cef70/download/win-32/symengine-0.3.0.353.g22cef70-vc14_0.tar.bz2'
Content type 'application/x-tar' length 993221 bytes (969 KB)
==================================================
downloaded 969 KB

trying URL 'https://anaconda.org/conda-forge/mpc/1.0.3/download/win-32/mpc-1.0.3-vc14_4.tar.bz2'
Content type 'application/x-tar' length 260611 bytes (254 KB)
==================================================
downloaded 254 KB

C:/Rtools/mingw_32/bin/gcc  -I"c:/R/include" -DNDEBUG -I../win-symengine/Library/include -I../win-mpc/Library/include -Ic:/local323/include -Ic:/local323/include         -O3 -Wall  -std=gnu99 -mtune=generic -c interface.c -o interface.o
C:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o symengine.dll tmp.def interface.o -L../win-symengine/Library/lib -L../win-mpc/Library/lib -Lc:/local323/lib//i386 -Lc:/local323/lib//i386 -lsymengine -lmpc -lmpfr -lgmp -Lc:/R/bin/i386 -lR
installing to C:/projects/symengine-r-xb3fo/symengine.Rcheck/symengine/libs/i386
** R
** preparing package for lazy loading
** help
No man pages found in package  'symengine' 
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for 'symengine' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/projects/symengine-r-xb3fo/symengine.Rcheck/symengine/libs/i386/symengine.dll':
  LoadLibrary failure:  The specified procedure could not be found.

Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/projects/symengine-r-xb3fo/symengine.Rcheck/symengine'
In R CMD INSTALL
```

**Comment by Marlin-Na** [comment]
Hi @isuruf , it seems that https://anaconda.org/conda-forge/gmp/files does not have windows binaries for gmp. Is there any other place I can download it?

**Comment by isuruf** [comment]
See https://anaconda.org/conda-forge/mpir/files. MPIR is a fork of gmp with windows builds.

**Comment by Marlin-Na** [comment]
Move to #20 , closing.

**Pull request closed without merging**
